project_name: hello_printer
root_path: ./src  # a relative path in this case implies you will run the `ragmatic` command within this same directory
components:
  document_sources:
    local_python_package:
      type: pycode_filesystem
      config:
        root_path: ./src
    localpy_storage:
      type: storage
      config: localpy
  storage:
    localpy:
      data_type: omni
      type: pydict
      config:
        dirpath: ./data  # a relative path in this case implies you will run the `ragmatic` command within this same directory
        overwrite: True
  llms:
    openai:
      type: openai
      config:
        api_keyenvvar: OPENAI_API_KEY
  summarizers:
    pycode:
      type: python_code
      config:
        llm: openai
  encoders:
    plaintext:
      type: hugging_face
      config:
        model_name: "dunzhang/stella_en_1.5B_v5"
        tokenizer_config:
          return_tensors: pt
          max_length: 1024
          truncation: True
          padding: max_length
        save_model: False
  rag_agents:
    pycode:
      type: python_code
      config:
        llm: openai
        storage: localpy
        encoder: plaintext
pipelines:
  ingest-python-codebase:
    - action: summarize
      config:
        root_path: ./src
        summarizer: pycode
        storage: localpy
        document_source: local_python_package
    - action: encode
      config:
        encoder: plaintext
        document_source: localpy_storage
        storage: localpy
rag_query_command:
  rag_agent: pycode
  document_source: local_python_package
  